import LogoImg from "./logoImg.png"
import HeroBg from "./heroBg.png"
import GetReady from "./GetReadyBg.png"
import GetReadyImg from "./getStartImg.png"
import FooterImg1 from "./footerImg1.png"
import FooterImg2 from "./footerImg2.png"
import FooterBg from "./footerBg.png"
import HeroImg1 from "./heroimg1.png"
import HeroImg2 from "./heroimg2.png"
import HeroImg3 from "./heroimg3.png"
import HeroImg4 from "./heroimg4.png"
import HeroImg5 from "./heroimg5.png"
import HeroImg6 from "./heroimg6.png"
import HeroImg7 from "./heroimg7.png"
import HeroImg8 from "./heroimg8.png"
import HeroImg9 from "./heroimg9.png"
import HeroImg10 from "./heroimg10.png"
import HeroImg11 from "./heroimg11.png"
import HeroImg12 from "./heroimg12.png"
import HeroImg13 from "./heroimg13.png"

export {LogoImg, HeroBg, GetReady, GetReadyImg, FooterImg1, FooterImg2, FooterBg, HeroImg1, HeroImg2, HeroImg3, HeroImg4, HeroImg5, HeroImg6, HeroImg7, HeroImg8, HeroImg9, HeroImg10, HeroImg11, HeroImg12, HeroImg13}